name: fastapi-test-ci

on:  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - 
        name: Loading file from S#
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://damg-7245-projects/data-store/airflow_scrape_data.db
          destination: ./fast-api/airflow_scrape_data.db
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: us-east-1
      -
        name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - 
        name: Install pipenv
        run: pip install pipenv
      - 
        name: Run tests
        working-directory: ./fast-api
        run: |
          pipenv install -r requirements.txt
          pipenv run pytest -v
        # Running pytest