name: CI-UnitTesting

on:  
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.12
      - name: Run tests
        run: |
          pip install -r requirements.txt
          pytest -v streamlit_test.py